# Generated by Django 3.2 on 2022-05-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='id_import',
        ),
        migrations.AddField(
            model_name='ticker',
            name='logo_url',
            field=models.CharField(default=False, max_length=500, verbose_name='ID Importação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='name',
            field=models.CharField(default=False, max_length=250, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(default=False, max_length=250, verbose_name='Ticker'),
            preserve_default=False,
        ),
    ]
