# Generated by Django 3.2 on 2022-05-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_auto_20220504_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
