# Generated by Django 3.2 on 2022-05-04 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticker', '0003_delete_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Aualizado em')),
                ('logo_url', models.CharField(max_length=500, verbose_name='ID Importação')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('ticker', models.CharField(max_length=250, verbose_name='Ticker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
