# Generated by Django 3.2 on 2022-05-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='ticker',
            name='currentvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='logo',
            field=models.CharField(default='', max_length=500, verbose_name='ID Importação'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='max2Weeks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maximo da Semana'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='min2Weeks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimo da Semana'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='site',
            field=models.CharField(default='', max_length=500, verbose_name='Site'),
        ),
    ]
