# Generated by Django 3.2 on 2022-05-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0005_auto_20220515_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='_yield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Média'),
        ),
    ]
