# Generated by Django 3.2 on 2022-05-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0006_ticker__yield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='max2Weeks',
            new_name='max2weeks',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='min2Weeks',
            new_name='min2weeks',
        ),
    ]
