# Generated by Django 3.2 on 2022-05-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0007_auto_20220515_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='_yield',
            new_name='media',
        ),
    ]
