# Generated by Django 3.2 on 2022-05-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0008_rename__yield_ticker_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='currentvalue',
            new_name='close',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='max2weeks',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='media',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='min2weeks',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='site',
        ),
    ]
