# Generated by Django 3.2 on 2022-05-16 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0009_auto_20220515_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='ranges',
            field=models.CharField(default='', max_length=350, verbose_name='Range'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='logo',
            field=models.CharField(default='', max_length=1000, verbose_name='ID Importação'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(max_length=450, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=10, verbose_name='Ticker'),
        ),
        migrations.CreateModel(
            name='HistoricTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(verbose_name='Data')),
                ('low', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Min')),
                ('high', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Max')),
                ('close', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic_ticker_related', to='ticker.ticker')),
            ],
        ),
    ]
