# Generated by Django 3.2 on 2022-05-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0011_auto_20220515_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='media',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Media do dia'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Minimo da dia'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Maximo do dia'),
        ),
    ]
